/cable_robot/core:
  ros__parameters:
    n_cables: 4
    controlUpdateInterval: 1e-4
    frame:
      color: Yellow
      lower: [ -2.0, -2.0, 0.0 ]
      radius: 0.02
      type: box
      upper: [ 2.0, 2.0, 4.0 ]
    joints:
      actuated: { damping: 1., effort: 100., min: 5., velocity: 10. }
      passive: { damping: 0.01., effort: 100., velocity: 10. }
    platform:
      color: Blue
      inertia: [ 1., 1., 1., 0., 0., 0. ]
      mass: 1.0
      position:
        rpy: [ 0., 0., 0. ]
        xyz: [ 0., 0., 2. ]
      size: [ 0.4, 0.4, 0.1 ]
      type: box
      visual: box
    points:
      frame0: [ -2.0, -2.0, 4.0 ]
      platform0: [ -0.2, -0.2, 0.0 ]
      frame1: [ -2.0, 2.0, 4.0 ]
      platform1: [ -0.2, 0.2, 0.0 ]
      frame2: [ 2.0, 2.0, 4.0 ]
      platform2: [ 0.2, 0.2, 0.0 ]
      frame3: [ 2.0, -2.0, 4.0 ]
      platform3: [ 0.2, -0.2, 0.0 ]
