/cable_robot/gcu:
  ros__parameters:
    debugInterval: 2e-1  # timer interval for debug info
    controlUpdateInterval: 1e-4  # timer interval for controls update
    areaSideX: 4.0  # x size of side of area
    areaSideY: 4.0  # y size of side of area
    areaSideZ: 4.0  # z size of side of area
    maxSpeed: 3.0  # maximum speed of platform
